# Tensors

- Tensors can be 1D, 2D or 3D or more
- In pytorch , every data structure is a tensor

## Creating Tensors

- tensor_object.size() will give size of a tensor
- tensor_object.numpy() to convert it into a numpy array
- torch.from_numpy() to convert a numpy array into a tensor

In [1]:
import torch

# create a empty tensor
print(torch.empty(2,2,2,dtype=torch.int)) # Named argument dtype is used to specify the data type

# create a tensor filled with zeros
print(torch.zeros(2,2,2))

# create a tensor filled with ones
print(torch.ones(2,2,2))

#create a tensor filled with random values
print(torch.rand(2,2,2))

# create a tensor from a list.
print(torch.tensor([[1,2,3],[4,5,6]]))


tensor([[[-1837100640,        1007],
         [          0,           0]],

        [[          0,           0],
         [          0,           0]]], dtype=torch.int32)
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[0.1394, 0.4119],
         [0.9445, 0.7900]],

        [[0.3532, 0.1786],
         [0.7727, 0.0937]]])
tensor([[1, 2, 3],
        [4, 5, 6]])


## Operations with tensors

In [2]:
# add
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a+b)

# using built in method
print(torch.add(a,b))

# performing inplace
a.add_(b)
print(a)  # Here any operation with trailing underscore, performs inplace.

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [3]:
# Subtraction

a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a-b)

# using built in method
print(torch.sub(a,b))

# performing inplace
a.sub_(b)
print(a)  # Here any operation with trailing underscore, performs inplace.

tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])


In [4]:
# multiplication

a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a*b)  

# using built in method
print(torch.mul(a,b))

# performing inplace
a.mul_(b)
print(a)  # Here any operation with trailing underscore, performs inplace.

tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [5]:
# division

a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a/b)

# using built in method
print(torch.div(a,b))

# performing inplace
a.div_(b)
print(a)  # Here any operation with trailing underscore, performs inplace.

tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


RuntimeError: result type Float can't be cast to the desired output type Long

# Slicing and Indexing tensors

In [6]:
x = torch.rand(5,3)

print(x[:,0]) #rows, col

tensor([0.6770, 0.9574, 0.3509, 0.5268, 0.5300])


In [7]:
# extracting only one value
print(x[1,1])

print(x[1,1].item())    

tensor(0.1699)
0.16989976167678833


# Resizing Tensors

- We use .view() in order to resize tensors
- -1 is a placeholder, the library will determine the correct value to be placed at -1 

In [9]:


a = torch.tensor([[1,2,3],[4,5,6]])
print(a)

# flatten a tensor
print(a.view(-1))

# Create a 2 column tensor
print(a.view(-1,2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


# GPU specific operations

In [ ]:
if torch.cuda.is_available:
    
    #create an instance for the gpu
    device=torch.device("cuda")
    
    # To use GPU, place tensors on the gpu. This can be inplace or transfer
    # inplace
    a = torch.tensor([1,2,3],device=device)

    #transfer
    b=torch.tensor([1,2,3])
    b.to(device)